Fix empty sequence error
Error caused by typo:

Traceback (most recent call last):
  File "d:\IDP Process Mining\KI\Process-Mining-Random-Eventlog-Generator\random_eventlog_gen.py", line 906, in <module>
    person = ermittle_person(abteilung)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\IDP Process Mining\KI\Process-Mining-Random-Eventlog-Generator\random_eventlog_gen.py", line 859, in ermittle_person
    return random.choice(abteilungen_personen_zuordnung.get(abteilung, []))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Surface\AppData\Local\Programs\Python\Python312\Lib\random.py", line 347, in choice
    raise IndexError('Cannot choose from an empty sequence')
IndexError: Cannot choose from an empty sequence